import { Badge } from "@/components/ui/badge";
import { Cloud, CloudOff, CheckCircle2, RefreshCw, AlertCircle } from "lucide-react";
import { cn } from "@/lib/utils";

export type Provenance =
  | "offline_draft"
  | "pending_cloud"
  | "cloud_verified"
  | "sync_failed"
  | "rule_based";

interface Props {
  provenance: Provenance;
  className?: string;
}

const CONFIG: Record<
  Provenance,
  { label: string; icon: typeof Cloud; classes: string; title: string }
> = {
  offline_draft: {
    label: "Offline draft",
    icon: CloudOff,
    classes: "bg-amber-100 text-amber-900 border-amber-300",
    title: "Captured locally. Will be reviewed by AI when the device is online.",
  },
  pending_cloud: {
    label: "Pending review",
    icon: RefreshCw,
    classes: "bg-blue-100 text-blue-900 border-blue-300",
    title: "Queued for cloud AI review.",
  },
  cloud_verified: {
    label: "Cloud verified",
    icon: CheckCircle2,
    classes: "bg-emerald-100 text-emerald-900 border-emerald-300",
    title: "AI-processed and available for clinician review.",
  },
  sync_failed: {
    label: "Sync failed",
    icon: AlertCircle,
    classes: "bg-red-100 text-red-900 border-red-300",
    title: "Last sync attempt failed. Will retry automatically.",
  },
  rule_based: {
    label: "Rule-based",
    icon: Cloud,
    classes: "bg-slate-100 text-slate-900 border-slate-300",
    title: "Generated by on-device mhGAP decision rules. Not an AI diagnosis.",
  },
};

export function ProvenanceBadge({ provenance, className }: Props) {
  const c = CONFIG[provenance];
  const Icon = c.icon;
  return (
    <Badge
      variant="outline"
      title={c.title}
      className={cn("gap-1 text-[10px] font-medium", c.classes, className)}
    >
      <Icon className="h-3 w-3" />
      {c.label}
    </Badge>
  );
}
