import { Button } from "@/components/ui/button";
import { Copy, Check, Download, ClipboardList, Trash2 } from "lucide-react";
import { useState } from "react";
import { MSESection } from "./MSESection";
import { SafetyAlert } from "./SafetyAlert";
import { useToast } from "@/hooks/use-toast";
import { exportAssessmentToPDF } from "@/lib/pdfExport";
import { Badge } from "@/components/ui/badge";

interface ClinicalAbstractProps {
  result: {
    hasRedAlert?: boolean;
    alertMessage?: string;
    translation?: string;
    culturalNotes?: string[];
    appearance?: string;
    speech?: string;
    mood?: string;
    perception?: string;
    risk?: string;
    fullText?: string;
    mse?: any;
    clinical_impressions?: string;
  } | null;
  narrative?: string;
  assessmentDate?: string;
  patientData?: any;
  languageDetected?: string;
  culturalIdioms?: string[];
  riskLevel?: string;
  onClear?: () => void;
}

export const ClinicalAbstract = ({ 
  result, 
  narrative = "",
  assessmentDate = new Date().toISOString(),
  patientData,
  languageDetected,
  culturalIdioms,
  riskLevel,
  onClear
}: ClinicalAbstractProps) => {
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();
  
  // Check if narrative contains screening context
  const hasScreeningContext = narrative.includes("SCREENING CONTEXT FOR MSE:");

  const handleExportPDF = () => {
    if (!result) return;

    const assessmentData = {
      narrative,
      processed_result: result,
      assessment_date: assessmentDate,
      language_detected: languageDetected,
      cultural_idioms_found: culturalIdioms,
      risk_level: riskLevel,
      patient: patientData,
    };

    exportAssessmentToPDF(assessmentData);
    toast({
      title: "PDF Exported",
      description: "Assessment report has been downloaded",
    });
  };

  const handleCopy = () => {
    if (!result) return;
    
    const textToCopy = `
MENTAL STATE EXAMINATION ABSTRACT
Assessment Date: ${new Date(assessmentDate).toLocaleDateString("en-ZA", { year: "numeric", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit" })}
${patientData?.patient_identifier ? `Patient ID: ${patientData.patient_identifier}\n` : ''}

${result.hasRedAlert ? `⚠️ RED ALERT: ${result.alertMessage}\n` : ''}
${result.translation ? `\nTRANSLATION:\n${result.translation}\n` : ''}
${result.culturalNotes && result.culturalNotes.length > 0 ? `\nCULTURAL CONTEXT:\n${result.culturalNotes.map(note => `• ${note}`).join('\n')}\n` : ''}

MENTAL STATE EXAMINATION:

Appearance & Behaviour:
${result.appearance || 'Not documented'}

Speech & Thought Stream:
${result.speech || 'Not documented'}

Mood & Affect:
${result.mood || 'Not documented'}

Perception (Hallucinations/Illusions):
${result.perception || 'Not documented'}

Risk Assessment (Suicide/Homicide/Self-harm):
${result.risk || 'Not documented'}

${result.clinical_impressions ? `\nCLINICAL IMPRESSIONS:\n${result.clinical_impressions}\n` : ''}

--- END OF CLINICAL ABSTRACT ---
This document is for medical records use only.
Generated by Nzwisiso Clinical Scribe
    `.trim();

    navigator.clipboard.writeText(textToCopy);
    setCopied(true);
    toast({
      title: "Copied to clipboard",
      description: "Clinical abstract ready for medical records",
    });
    setTimeout(() => setCopied(false), 2000);
  };

  if (!result) {
    return (
      <div className="flex items-center justify-center h-full text-muted-foreground">
        <div className="text-center space-y-2">
          <p className="text-lg font-medium">No analysis yet</p>
          <p className="text-sm">Process a patient narrative to see the clinical abstract</p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between mb-2">
        <h2 className="text-lg font-semibold text-foreground">Clinician's Abstract (MSE Format)</h2>
        <div className="flex gap-2">
          {onClear && (
            <Button
              variant="outline"
              size="sm"
              onClick={onClear}
              className="text-destructive hover:text-destructive-foreground hover:bg-destructive"
            >
              <Trash2 className="h-4 w-4 mr-2" />
              Discard Result
            </Button>
          )}
          {hasScreeningContext && (
            <Badge variant="secondary" className="mr-2">
              <ClipboardList className="h-3 w-3 mr-1" />
              Screening-informed
            </Badge>
          )}
          <Button
            variant="outline"
            size="sm"
            onClick={handleExportPDF}
            className="text-primary hover:text-primary-foreground hover:bg-primary"
          >
            <Download className="h-4 w-4 mr-2" />
            Export PDF
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={handleCopy}
            className="text-primary hover:text-primary-foreground hover:bg-primary"
          >
            {copied ? (
              <>
                <Check className="h-4 w-4 mr-2" />
                Copied
              </>
            ) : (
              <>
                <Copy className="h-4 w-4 mr-2" />
                Copy for Medical Records
              </>
            )}
          </Button>
        </div>
      </div>

      {result.hasRedAlert && result.alertMessage && (
        <SafetyAlert message={result.alertMessage} />
      )}

      {result.translation && (
        <div className="p-4 bg-accent/50 rounded-lg border border-border">
          <h3 className="font-semibold text-sm text-accent-foreground mb-2">Translation</h3>
          <p className="text-sm text-muted-foreground">{result.translation}</p>
        </div>
      )}

      {result.culturalNotes && result.culturalNotes.length > 0 && (
        <div className="p-4 bg-clinical-green-light/30 rounded-lg border border-border">
          <h3 className="font-semibold text-sm text-clinical-green-dark mb-2">Cultural Context</h3>
          <ul className="list-disc list-inside space-y-1">
            {result.culturalNotes.map((note, i) => (
              <li key={i} className="text-sm text-muted-foreground">{note}</li>
            ))}
          </ul>
        </div>
      )}

      <div className="space-y-3">
        <MSESection title="Appearance & Behaviour" content={result.appearance || "Not documented"} />
        <MSESection title="Speech & Thought Stream" content={result.speech || "Not documented"} />
        <MSESection title="Mood & Affect" content={result.mood || "Not documented"} />
        <MSESection title="Perception (Hallucinations/Illusions)" content={result.perception || "Not documented"} />
        <MSESection 
          title="Risk Assessment (Suicide/Homicide/Self-harm)" 
          content={result.risk || "Not documented"} 
        />
      </div>

      {result.clinical_impressions && (
        <div className="mt-4 p-4 bg-accent/20 rounded-lg border border-border">
          <h3 className="font-semibold text-sm text-foreground mb-2">Clinical Impressions</h3>
          <p className="text-sm text-muted-foreground whitespace-pre-wrap">{result.clinical_impressions}</p>
        </div>
      )}
    </div>
  );
};